import type {Metadata} from "next";
import "./globals.css";
import {Header} from "@/components/navbar/header";
import {AuthProvider} from "@/app/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
          className={"bg-background text-text font-sans"}
      >
      <AuthProvider>
      <Header/>
      {children}
      </AuthProvider>
      </body>
    </html>
  );
}
